export const subjects = [
  "ENGLISH LANGUAGE",
  "INTEGRATED SCIENCE",
  "MATHEMATICS",
  "SOCIAL STUDIES",
  "RELIGIOUS AND MORAL",
  "INFORMATION AND COMMUNICATION TECHNOLOGY",
  "FRENCH LANGUAGE",
  "CREATIVE ARTS",
  "GHANAIAN LANGUAGE",
  "CAREER TECHNOLOGY",
];
