export const subjects = [
  "ENGLISH LANGUAGE",
  "INTEGRATED SCIENCE",
  "MATHEMATICS",
  "SOCIAL STUDIES",
  "RELIGIOUS & MORAL EDUCATION",
  "INFORMATION & COMM. TECHNOLOGY",
  "FRENCH LANGUAGE",
  "CREATIVE ARTS",
  "GHANAIAN LANGUAGE",
  "CAREER TECHNOLOGY",
];
